runtime: java17
env: standard
instance_class: B1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  cool_down_period_sec: 60
service_account: organic-byway-391719@appspot.gserviceaccount.com
env_variables:
  jdbcURL: "jdbc:postgresql://google/ipc"
  cloudSqlInstance: "organic-byway-391719:europe-southwest1:ipc"
  postgresql_username: "ipc"
  postgresql_password: "postgresql"
