TRUNCATE TABLE dbo.USERS cascade;
TRUNCATE TABLE dbo.MONITORS cascade;
TRUNCATE TABLE dbo.CLIENTS cascade;
TRUNCATE TABLE dbo.TOKENS cascade;
TRUNCATE TABLE dbo.MONITOR_RATING cascade;
TRUNCATE TABLE dbo.DOCS_AUTHENTICITY cascade;
TRUNCATE TABLE dbo.PLANS cascade;
TRUNCATE TABLE dbo.CLIENT_PLANS cascade;
TRUNCATE TABLE dbo.DAILY_LISTS cascade;
--TRUNCATE TABLE dbo.EXERCISES_INFO cascade;
TRUNCATE TABLE dbo.client_to_monitor cascade;
TRUNCATE TABLE dbo.DAILY_EXERCISES cascade;
TRUNCATE TABLE dbo.EXERCISES_VIDEO cascade;
TRUNCATE TABLE dbo.monitor_requests cascade;

ALTER SEQUENCE dbo.daily_exercises_id_seq RESTART WITH 1;
ALTER SEQUENCE dbo.daily_lists_id_seq RESTART WITH 1;
ALTER SEQUENCE dbo.plans_id_seq RESTART WITH 1